services:
  - type: web
    name: straika-sports
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT run:app"
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: app.db
          property: connectionString
      - key: FLASK_APP
        value: "run.py"