"""changed pageview to delete all view data

Revision ID: d3bef997f574
Revises: ea4b84c3f4e2
Create Date: 2025-07-04 16:59:54.112994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bef997f574'
down_revision = 'ea4b84c3f4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pageview_post_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pageview_post_id', 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pageview_post_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pageview_post_id'), 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
